name: Auto Update Store

on:
  push:
    paths:
      - 'feed/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Update Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_store.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add files/ json/ feed/
          git status
          git diff --quiet && git diff --staged --quiet || (git commit -m "auto: update store files, JSONs and OPML exports [skip ci]" && git push)
